version: "3.7"

services:
  ci-cd-test-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ci-cd-test-app
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
